# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_scan_seq <- function(cons, the_seq, the_pattern, fix_with) {
    .Call('_hypermutR_rcpp_scan_seq', PACKAGE = 'hypermutR', cons, the_seq, the_pattern, fix_with)
}

