# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_scan_seq_int <- function(r_cons, r_the_seq, r_fix_with) {
    .Call('_hypermutR_rcpp_scan_seq_int', PACKAGE = 'hypermutR', r_cons, r_the_seq, r_fix_with)
}

